### ISSUE TITLE
How to add an icon to an input box

### ISSUE THREAD

**Issue by pford68** [pford68/playground#16]
## Without Bootstrap
You can do this with CSS by absolutely positioning the icon inside of the input element. Then add padding to either side so the text doesn't overlap with the icon.

### The HTML part
```html
<div class="form-control form-control-user">
   <input type="text" name="user" placeholder="user@mydomain.com" />
   <img src="images/ibm-design-icons/png/glyphs/user_24.png">
</div>
```

### The CSS part
```css
.form-control{
   height: 30px;
}

.form-control-user {
  position:relative;
  padding:0;
  margin:0;
}

.form-control-user input {
  height:100%;
  margin:0;
  padding-left: 30px;
}

.form-control-user img {
  position:absolute;
  bottom:4px;
  left:10px;
  width:15px;
  height:15px;
}
```

## References
* https://stackoverflow.com/questions/18838964/add-bootstrap-glyphicon-to-input-box/19918345#19918345
