### ISSUE TITLE
How to make DIV no larger than its contents?

### ISSUE THREAD

**Issue by pford68** [pford68/playground#17]
Set the DIV's `display` CSS property to `inline-block`.

```css
.form-control-basic {
  position: relative;
  padding: 0;
  margin: 0;
  display: inline-block;
}
```

## References
* https://stackoverflow.com/questions/450903/how-to-make-div-not-larger-than-its-contents
